version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  tema-08:
    image: 74618f280966   # O ID do contêiner MongoDB
    container_name: tema-08
    ports:
      - "8081:8081"
    links:
      - mongodb
